apiVersion: v2
name: mysql
description: Production-grade MySQL StatefulSet Helm chart
type: application
version: 0.1.0
appVersion: "8.0.36"
keywords: [mysql, database, statefulset]
maintainers:
  - name: kube-platform
home: https://github.com/sanskarpan/Kubernetes
sources:
  - https://hub.docker.com/_/mysql
