#!/usr/bin/env bash
set -euo pipefail

# ==============================================================================
# seal-secret.sh — Seal a Kubernetes Secret using kubeseal
# ==============================================================================
# Usage:
#   ./seal-secret.sh <secret-name> <namespace> [key=value ...]
#
# Examples:
#   ./seal-secret.sh app-secret workloads DB_PASSWORD=mypassword API_KEY=xyz
#   ./seal-secret.sh db-credentials production DB_HOST=db.example.com DB_PORT=5432
#
# Prerequisites:
#   - kubectl configured with access to the target cluster
#   - kubeseal installed (brew install kubeseal or see sealed-secrets/README.md)
#   - sealed-secrets-controller running in kube-system
#
# Output:
#   SealedSecret YAML printed to stdout. Redirect to a file to save:
#   ./seal-secret.sh app-secret workloads DB_PASSWORD=secret > sealed-app-secret.yaml
#
# The output file IS safe to commit to Git. The encrypted values can only be
# decrypted by the sealed-secrets controller in your cluster.
# ==============================================================================

SECRET_NAME="${1:?Usage: $0 <secret-name> <namespace> [key=value ...]}"
NAMESPACE="${2:?Usage: $0 <secret-name> <namespace> [key=value ...]}"
shift 2

# Check required tools are available
for tool in kubectl kubeseal; do
  if ! command -v "${tool}" &>/dev/null; then
    echo "ERROR: '${tool}' is not installed or not in PATH" >&2
    exit 1
  fi
done

# Check that the target namespace exists (warn if not — kubeseal will still work
# but the resulting SealedSecret will be namespace-scoped to a non-existent namespace)
if ! kubectl get namespace "${NAMESPACE}" &>/dev/null; then
  echo "WARNING: namespace '${NAMESPACE}' does not exist in the current cluster context." >&2
  echo "         The SealedSecret will still be created but cannot be applied until" >&2
  echo "         the namespace exists." >&2
fi

# Build kubectl command for literal values
KUBECTL_ARGS=()
for kv in "$@"; do
  KUBECTL_ARGS+=(--from-literal="${kv}")
done

if [[ ${#KUBECTL_ARGS[@]} -eq 0 ]]; then
  echo "ERROR: At least one key=value pair is required." >&2
  echo "Usage: $0 <secret-name> <namespace> [key=value ...]" >&2
  exit 1
fi

echo "# SealedSecret generated by seal-secret.sh" >&2
echo "# Secret name: ${SECRET_NAME}" >&2
echo "# Namespace:   ${NAMESPACE}" >&2
echo "# This file is safe to commit to Git." >&2
echo "" >&2

kubectl create secret generic "${SECRET_NAME}" \
  --namespace "${NAMESPACE}" \
  --dry-run=client \
  -o yaml \
  "${KUBECTL_ARGS[@]}" \
| kubeseal \
  --namespace "${NAMESPACE}" \
  --format yaml
