---
apiVersion: v1
kind: Namespace
metadata:
  name: notes-app
  labels:
    app.kubernetes.io/name: notes-app
    app.kubernetes.io/part-of: kube-platform
    # Pod Security Standards: enforce restricted policy
    # Pods must be non-root, have seccompProfile, drop all capabilities
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
  annotations:
    kubernetes.io/description: "Namespace for the Django Notes application"
